services:
  nginx:
    depends_on:
      - frontend
      - api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    

  api:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    expose:
      - "3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
