version: '3.8'

services:
  nginx:
    depends_on:
      - frontend
      - api
    restart: always
    image: ${DOCKERHUB_USERNAME}/jobsmatch-nginx:latest
    ports:
      - "80:80"

  api:
    platform: linux/amd64
    image: ${DOCKERHUB_USERNAME}/jobsmatch-api:latest
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    image: ${DOCKERHUB_USERNAME}/jobsmatch-frontend:latest
    expose:
      - "80"
